{
    #finetune specific settings
    load_optimizer: false,    
    weight_decay: 0.1,
    save_every: 250,

    # image encoder settings
    encoder_name: 'clip_resnet_large',
    adapter_config: {"mlp": {"adapter_type": "normal", "downsample_factor": 8}, "attention": {"adapter_type": "normal", "downsample_factor": 8}},
    freeze_img_encoder: false,
    
    # train settings 
    batch_size: 256,
    train_steps: 5000,
    lr: 0.000315,  
    min_lr: 0.0,
    lr_decay_iters: 6000,
    image_enc_lr: 1.5e-6,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1, 
    freeze_img_encoder_batchnorms: false,
    image_size: 384,

    gradient_accumulation_steps: 8,
    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    dataset_type: 'nlvr2',
    train_dataset_dir: '/mnt/localdisk/nlvr2',
    eval_dataset_dir: '/mnt/localdisk/nlvr2',

    vqa_dir: "/mnt/localdisk/vqa_val_converted",
    gqa_dir: "/mnt/localdisk/gqa_val_converted",
    
    save: "/mnt/shared_vol/checkpoints/MAGMA_RN50x16_nlvr2",
    load: "/mnt/shared_vol/checkpoints/MAGMA_RN50x16_nlvr2",

    eval_every: 100,
    wandb_project: "multimodal_finetuning",
    name: "MAGMA_RN50x16_v1_nlvr2",

    class_dict: {"num_classes": 2, "pretrained_checkpoint": "/mnt/shared_vol/checkpoints/MAGMA_RN50x16/global_step30000/mp_rank_00_model_states.pt"}

}
